### ISSUE TITLE
invalid_grant while generating the refresh token

### ISSUE THREAD

**Issue by pramodwagh** [webfox/laravel-xero-oauth2#32] opened 2020-09-17 01:54 UTC
Hello,
Please help me to resolve it. Yesterday it was work fine but when I again test it throws error like invalid_grant.
Also, I found that when I ran command composer, install it shows same error like invalid_grant.

**Comment by a-tesh** [comment] 2020-09-17 14:05
I have also encountered this today. I believe it was working yesterday also.

**Comment by a-tesh** [comment] 2020-09-17 14:30
@pramodwagh I deleted the xero.json file from storage/framework and this has fixed things for now.

Looks like there's an issue renewing the token?

**Comment by hailwood** [comment] 2020-09-17 21:18
Hi @pramodwagh & @a-tesh,

Are you also having issues with the initial connection, or just the refresh? Is it still not working today? (The tokens are only valid for 30 minutes so it should have forced a refresh).

**Comment by pramodwagh** [comment] 2020-09-18 00:55
@hailwood No I am not having this issue in initial connection. It is just with refresh token.
If token expire after 30 min do we need to reconnect again with Xero? also once token expired and I am trying to reconnect with Xero still getting the same error.

overall ultimate question:- what are the steps needs to be done if token expired?

**Comment by pramodwagh** [comment] 2020-09-18 00:59
@a-tesh yes we can do this but the problem is if there is any solution apart from this that's could be better because it is not possible to every time we delete the file and reconnect again. If you find other solution please let us know.

**Comment by kunallibra** [comment] 2020-10-04 10:26
> renewing

Hi i tried to delete the xero.json file but i still get this error:


 

connected | **false**
error | **null**
organisationName | **null**
username | **null**

is there any way i can regenerate the file and save these token crap again?

**Comment by hailwood** [comment] 2020-10-06 20:52
This is a strange one and we've got two separate issues going on here.
For the issue renewing the token, we're going to have to call in @SidneyAllen and see if he's got any thoughts on why it might be failing only on the refresh token and only for a subset of users as we're using the exact code the standard php library is using.

@kunallibra if the file is gone that's the only place we store the credentials (unless you're using the CacheStore), so you should be able to connect as if it was a fresh install.

**Comment by SidneyAllen** [comment] 2020-10-13 18:02
@hailwood - I am not certain why a subset of users would get an invalid_grant when refreshing tokens.

I do recommend watching a recent video we published on common errors when using OAuth 2.  It discuss the potential causes for invalid grants and suggestions for debugging.  I suspect it's a token management issue.

https://youtu.be/N-ZuKFvYjfw?t=71

**Comment by hailwood** [comment] 2020-11-02 09:20
I'm going to close this issue now as unless I can get a small demo app that I can use to reproduce this issue, there's unfortunately no way I can really debug this.

If anyone manages  create a demo with a way to consistently reproduce this issue, please ping me and I'll reopen this issue.

**Closed by hailwood** 2020-11-02 09:20 UTC
